<a href="https://colab.research.google.com/github/matthewjtate79/RNN-for-Stock-Prediction/blob/main/RNNTest.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
def tanh(z):


def tanh_prime(z):


In [ ]:
def RNN(X, y, num_hidden, learning_rate):
  num_features = X.shape[1]
  input_size = X.shape[0]

  # Weight matrix for inputs
  W = np.zeros((num_features, num_hidden))
  # Weight matrix for hidden layer of previous timestep
  U = np.zeros((num_hidden, num_hidden))
  # Weight matrix for projecting hidden layer into output layer
  V = np.zeros(num_hidden)

  H_prev = np.zeros(num_hidden)
  b_h = np.zeros(num_hidden)
  b_o = np.zeros(1)

  for i in range(0, input_size):
    # Get the results of the hidden layer
    H_curr = X[i] @ W + H_prev @ U + b_h
    H_prev = H_curr

    # Get the results of the output layer
    Output = H_curr @ V + b_o

    # Calculates the mean squared error
    Loss = pow(y[i] - Output[0], 2)

    # Updates the weights and bias for output layer
    gradient_b = -2 * (y[i] - Output[0])
    gradient_V = -2 * (y[i] - Output[0]) * V
    b_o = b_o - learning_rate * gradient_b
    V = V - learning_rate * gradient_V






X = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])
y = np.array([10, 11, 12])

RNN(X, y, 16, 0.001)

100.0
[0.02]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
120.56040000000002
[0.04196]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
142.9947206416
[0.06587608]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
